### ISSUE TITLE
SQLAlchemy integration

### ISSUE THREAD

**Issue by Gr1N** [aio-libs/aioodbc#118]
Hi,

What about SQLAlchemy integration like in [aiopg](https://github.com/aio-libs/aiopg#example-of-sqlalchemy-optional-integration)? Do you have any plans? Or it's already supported but missed in docs?

**Comment by jettify** [comment]
Sorry, not supported for now and I do not have plan to add, may be in future we will have async ORM that unifies all those libraries. PR is welcome.

**Comment by vproman** [comment]
I am planning on adding support for using SQLAlchemy Core as SQL query builder, like aiopg and aiomysql have.  Looking at the code, it seems the primary parts missing are the create_engine method and an Engine class.  Can you think of any pitfalls I am likely to run into if we go down this path?

**Comment by jettify** [comment]
Should be easy to do just copy `sa` module from `aiopg` or `aiomysql` and update dialect and other parameters.

**Comment by rohansb** [comment]
@jettify @vproman a pitfall that i encountered when replicating `sa` functionality:
The [asynchronous file descriptor](https://github.com/aio-libs/aiopg/blob/master/aiopg/connection.py#L112) such as available in aiopg, which is supported by [psycopg](http://initd.org/psycopg/docs/connection.html#connection.fileno) under the hood, Is Not supported by in pyodbc because of [this limitation](https://github.com/mkleehammer/pyodbc/issues/348#issuecomment-368080874)

@jettify Do you have any suggestions for a possible workaround that, in order to add SA support?

**Comment by jettify** [comment]
This is not an issue here at all, since we offload blocking operations into threads, and SQLA integration does not depend on any file descriptors.

**Comment by rohansb** [comment]
@jettify thanks for your response. That confirms i was headed down a wrong path, in trying to replicate the functionality without using the offloading. 

This is really the key finding for me! Could you please elaborate on "we offload blocking operations into threads" 

Is this something you can achieve using **ThreadPoolExecutor**? It seems its achieved using `run_in_executor` on the event loop. Do you mind pointing to a simplest **Example of how to offload blocking operations into threads?**

**Comment by rohansb** [comment]
I think i found an example i was looking for here: https://github.com/calebmadrigal/asyncio-examples/blob/master/run_in_executor.py 

Any more suggestions are welcomed! Thanks a bunch

**Comment by jettify** [comment]
This is pretty much only one call 
https://github.com/aio-libs/aioodbc/blob/948da6993b79d6a20620530e201de7353ad7f6a0/aioodbc/connection.py#L78-L82
we do it here. Official docs:
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.run_in_executor

As for SQLA you may want to check https://github.com/aio-libs/aiopg/tree/master/aiopg/sa it should be pretty straightforward to adapt.

**Comment by jettify** [comment]
Looked into `sqlalchemy` code there are pyodbc dialects only for: `mysql`, `mysql`, `sybase`.

**Comment by OdinTech3** [comment]
What is the status of this @jettify @vproman, has idea been dropped?

**Comment by jettify** [comment]
No plans to work on SQLA integration for now.
