### ISSUE TITLE
Upstream pyodbc issue

### ISSUE THREAD

**Issue by andrewbaxter** [aio-libs/aioodbc#162]
The upstream issue is: https://github.com/mkleehammer/pyodbc/issues/341

Would it be possible to pin the pyodbc version?  That way reinstalling dependent projects would be reliable and if a specific version is needed it can be overridden per project (and maintain relaibility).

And thanks for this project!  The world doesn't have enough async database clients.

**Comment by jettify** [comment]
Not sure about pinning, but we can exclude problematic release, something like `!=4.0.22`. Would you like to create PR?

**Comment by jettify** [comment]
New version of pyodbc==4.0.23 already available with proper fixes, I think we can close this issue.
