### ISSUE TITLE
MySQL connection (Question)

### ISSUE THREAD

**Issue by romkazor** [aio-libs/aioodbc#188]
Hello. How can i create a permanent connection to database with aiodbc and use it for all queries like this:
```
cnxn   = pyodbc.connect(...)
cursor = cnxn.cursor()
cursor.execute(...)
```
I don't want to create a new connection to the database every time to make a query.
Thanks.

**Comment by julianit** [comment]
You can create a singleton class  that keeps the connection open. The class should have a method that return the cursor i.e. def cursor(self): return self.conneciton.cursor(), as this is what you need in order to execute a query.

**Comment by romkazor** [comment]
Thanks. If you could write an some small example, its will be great.

**Comment by jettify** [comment]
https://github.com/aio-libs/aioodbc/blob/01245560828d4adce0d7d16930fa566102322a0a/examples/example_pool.py#L1-L22

**Comment by julianit** [comment]
This is how I use it:

`class DatabaseConnection:`

    instance = None
    def __init__(self, connection):
        self.connection = connection

    def cursor(self):
        "Form the cursor"
        return self.connection.cursor()

    @classmethod
    async def get(cls):
        "Return database connection"
        if cls.instance is None:
            connection = await connect("Connection detailes here - DSN")
            cls.instance = DatabaseConnection(connection)
        return cls.instance
