### ISSUE TITLE
no pypi wheel 

### ISSUE THREAD

**Issue by stonebig** [aio-libs/aioodbc#203]
would it be possible to have a wheel on pypi ? like aioodbc-0.3.3-py3-none-any.whl ?

**Comment by julianit** [comment]
I think, there is already: https://pypi.org/project/aioodbc/

**Comment by stonebig** [comment]
it's not a wheel 
![image](https://user-images.githubusercontent.com/4312421/66662026-576be500-ec48-11e9-9a82-0bf22031785c.png)

**Comment by julianit** [comment]
I see. I think, you can either install tar.gz file or convert it to whl using pip.
Why do you need  exactly wheel file?

**Comment by stonebig** [comment]
it avoids doing it myself. it's the recommanded modern packaging standard on pip now.

**Comment by asvetlov** [comment]
Do you have a problem on installing from tarball?
`pip install aioodbc` should works.

**Comment by stonebig** [comment]
hi @asvetlov , I did it. the wheel quest is to help moving pypi toward "conda-like" consistency, and avoiding excution at install. it's just a "python setup.py sdist bdist_wheel" + "twine upload  dist/*"

**Comment by asvetlov** [comment]
Sure, wheels are great.
I'm still curious what *real* problem do you want to solve?
What does not work now?

**Comment by stonebig** [comment]
everything works. Problem is to make the official packaging eco-system progress. and wheels are on that path.

**Comment by asvetlov** [comment]
If it's not broke don't fix it.
The next release will probably have a wheel because travis CI is configured to make it.
No reason to publish this release soon though.
