### ISSUE TITLE
Allow autocommit to be updated

### ISSUE THREAD

**Issue by plannigan** [aio-libs/aioodbc#269]
[pyodbc's autocommit field](https://github.com/mkleehammer/pyodbc/wiki/Connection#autocommit) can be set to change the autocommit state of the connection while it is open. Updating the property to allow the value to be set brings the implementation more in line with implementing the ["same api" as pyodbc](https://github.com/aio-libs/aioodbc#basic-example).

**Comment by jettify** [comment]
done
