### ISSUE TITLE
Is there any ORM library supported by aioodbc ?

### ISSUE THREAD

**Issue by basiltt** [aio-libs/aioodbc#364]
I'm trying to build an FastAPI application with using MSSQL, I couldn't find any ORM library supports aioodbc. Is there any library available ?

**Comment by SantosJMM** [comment]
Hello SqlAlchemy is a powerful ORM and supports mssql

**Comment by SantosJMM** [comment]
https://docs.sqlalchemy.org/en/14/dialects/mssql.html

**Comment by basiltt** [comment]
Yeah, but it doesn't support Async.

**Comment by SantosJMM** [comment]
https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html

**Comment by jettify** [comment]
Closing since ORM is out of scope.
