### ISSUE TITLE
package dead?

### ISSUE THREAD

**Issue by ConnorSMaynes** [aio-libs/aioodbc#381]
Apologies if this is not the place to ask, as I do not use Github often, but **is this package dead?**

It looks like there are ~20 open issues, some pretty important, and the last closed issue was in 12/2020.

**Comment by skewty** [comment]
This comment is now 6 months old with no reply and the last commit was 3 years ago. I am of the opinion that this project is dead. Is anyone interested in forking and taking ownership of the new repo?

**Comment by skewty** [comment]
@jettify are you able and willing to hand over this repo to a new maintainer?

Does anyone know him in real life / able to contact him through other means?

**Comment by cdoolin** [comment]
https://github.com/tortoise/asyncodbc.git looks like a fork with Python 3.9+ fixes

**Comment by kuwv** [comment]
@jettify ping

**Comment by jettify** [comment]
New version available on PyPI https://pypi.org/project/aioodbc/0.4.0/
